# Generated by Django 4.2.20 on 2025-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='clusters_json',
            field=models.TextField(blank=True, default='', help_text='JSON-serialized string of the cluster definition returned by data.graph.generate_match_clusters'),
        ),
    ]
